[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
